<?php
return [
    'lastname' => 'required',
    'firstname' => 'required',
    'middlename' => 'required',
    'class' => 'required',
    'dateOfbirth' => 'required',
    'degree' => 'required',
    'department' => 'required',
    'faculty' => 'required',
    'university_name' => 'required',
    'yearOfAdmission' => 'required',
    'yearOfgraduation' => 'required',
];

(`id` int(11) NOT NULL AUTO_INCREMENT,
          `firstname` varchar(45) DEFAULT NULL,
          `lastname` varchar(45) DEFAULT NULL,
          `middlename` varchar(45) DEFAULT NULL,
          `universityName` int(11) DEFAULT NULL,
          `graduation_year` int(11) DEFAULT NULL,
          `facultyName` int(11) DEFAULT NULL,
          `departmentName` int(11) DEFAULT NULL,
          `degreeType` int(11) DEFAULT NULL,
          `classType` int(11) DEFAULT NULL,
          `yearOfAdmission` int(11) DEFAULT NULL,
          `date_of_birth` date DEFAULT NULL,
          PRIMARY KEY (`id`),
          KEY `student_universityName` (`universityName`),
          KEY `student_graduating_year` (`graduation_year`),
          KEY `student_facultyName` (`facultyName`),
          KEY `student_departmentName` (`departmentName`),
          KEY `student_degreeType` (`degreeType`),
          KEY `student_classType` (`classType`),
          CONSTRAINT `student_classType` FOREIGN KEY (`classType`) REFERENCES `classes` (`id`),
          CONSTRAINT `student_degreeType` FOREIGN KEY (`degreeType`) REFERENCES `degrees` (`id`),
          CONSTRAINT `student_departmentName` FOREIGN KEY (`departmentName`) REFERENCES `departments` (`id`),
          CONSTRAINT `student_facultyName` FOREIGN KEY (`facultyName`) REFERENCES `faculties` (`id`),
          CONSTRAINT `student_universityName` FOREIGN KEY (`universityNAme`) REFERENCES `universities` (`id`)
        )";
